version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
    time: "17:00"
    timezone: Europe/Amsterdam
  open-pull-requests-limit: 10
  assignees:
  - lenscas
